# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProbitMCMCHSD <- function(i_Num_of_iterations, list_Data, logic_Robust, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara) {
    .Call(`_BayesRGMM_ProbitMCMCHSD`, i_Num_of_iterations, list_Data, logic_Robust, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara)
}

ProbitMCMCARMAKB <- function(i_Num_of_iterations, list_Data, logic_Robust, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara, ARMA_Order) {
    .Call(`_BayesRGMM_ProbitMCMCARMAKB`, i_Num_of_iterations, list_Data, logic_Robust, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara, ARMA_Order)
}

CumulativeProbitMCMC <- function(i_Num_of_iterations, list_Data, logic_Robust, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara) {
    .Call(`_BayesRGMM_CumulativeProbitMCMC`, i_Num_of_iterations, list_Data, logic_Robust, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara)
}

